spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
  
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client              # 微服务名称(注册进eureka中的名称)服务实例名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false              # 数据库连接
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.xyz.entity                      # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件
  
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      # 添加eureka服务集群地址
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001   # 此微服务的标识
    prefer-ip-address: true     #访问路径可以显示IP地址

# 微服务页面信息
info:
  app.name: xyz-config-microservicecloud-8001
  company.name: www.xioayuzhou.com
  build.artifactId: microservicecloud-provider-dept-8001
  build.version: 0.0.1-SNAPSHOT

---
server:
  port: 8001
  
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client              # 微服务名称(注册进eureka中的名称)服务实例名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB03?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false              # 数据库连接
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.xyz.entity                      # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件
  
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      # 添加eureka服务集群地址
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001  # 此微服务的标识
    prefer-ip-address: true     #访问路径可以显示IP地址

# 微服务页面信息
info:
  app.name: xyz-config-microservicecloud-8001
  company.name: www.xioayuzhou.com
  build.artifactId: microservicecloud-provider-dept-8001
  build.version: 0.0.1-SNAPSHOT

# 请保存UTF-8形式
